### PR TITLE
Improve `Debug` impl of `RpcStatusCode`

### LINKED ISSUE #432: Better Display impl for `grpcio::Error`
**Is your feature request related to a problem? Please describe.**
The current [Display implementation](https://docs.rs/grpcio/0.5.0-alpha.4/src/grpcio/error.rs.html#27-48) for `grpcio::Error` is:
```rust
impl Display for Error {
    fn fmt(&self, fmt: &mut Formatter<'_>) -> fmt::Result {
        write!(fmt, "{:?}", self)
    }
}
```
Unfortunatly this doesn't output a very user friendly error in the case of a RpcFailure `RpcFailure(RpcStatus { status: RpcStatusCode(13), details: Some("") })`, notably it forces the developer to know the mapping code to name for each RpcStatusCode. 

**Describe the solution you'd like**
Implement `Display` on `RpcStatus` and `RpcStatusCode` and update the impl for `Display` for grpcio::Error to:
```rust
impl Display for Error {
    fn fmt(&self, fmt: &mut Formatter<'_>) -> fmt::Result {
        match self {
            Error::RpcFailure(rpc_failure) => write!(fmt, "RpcFailure({})", rpc_failure),
            other_error => write!(fmt, "{:?}", other_error),
       }
    }
}
```

If you validate this solution I'll gladly submit a PR.

**Describe alternatives you've considered**

**Additional context**
Have a nice day !

### PR DESCRIPTION
**Pull request by Ten0**
Helps #432 

This is an complementary approach to #433 for improving the `Display` impl for `grpcio::Error`, which requires less code. It has the additional effect of improving the `RpcStatusCode` and `RpcStatus` debug displays.

Note that this doesn't make #433 unnecessary: #433 still improves the `Display` implementation for `grpcio::Error` compared to this.

Once this is merged though, #433 can be expressed in an easier way.

### CODE REVIEW

**Comment by BusyJay** [comment]
Now #433 is merged, I think you can delegate debug to display directly.

**Comment by Ten0** [comment]
I also very often use `Debug`, be it for some structures that wrap a grpc error and derive `Debug` or because I `dbg!` some `RpcStatus` at some point, and I'm pretty sure it's more useful to see what the status code corresponds to than the internal structure of `RpcStatusCode`, which anyway has only one field, and it's private.

Do you think it's more useful to have the current `Debug` display, and if so, why?

**Comment by BusyJay** [comment]
I think you get me wrong. I'm OK with the format you try to implement, I just suggest to implement it by delegating debug to display as they are essential the same code.

**Comment by Ten0** [comment]
Oh, right, I need to update this PR based on the fact #443 is merged 🙂

**Comment by Ten0** [comment]
Done

**Pull request merged**
